source "https://supermarket.chef.io"

cookbook 'apt', '>= 2.7.0'
cookbook 'yum', '>=v3.6.3'
cookbook 'yum-epel', '>= 0.3.6'
cookbook 'ark'
cookbook 'bluepill', '>= 2.3.1'
cookbook 'build-essential', '>= 1.4.2'
cookbook 'java', '>= 1.19.2'
cookbook 'ohai', '>= 1.1.12'
cookbook 'python', '>= 1.4.6'
cookbook 'rsyslog', '>= 1.11.0'
cookbook 'windows', '>= 1.30.0'
cookbook 'elasticsearch', '>= 0.3.13'
cookbook 'mongodb'
cookbook 'layer-custom'
